### ISSUE TITLE
Can't find help

### ISSUE THREAD

**Issue by fletchwsf** [juli1/emfta#19]
The installation instructions on github state that help files are available under the Eclipse help in a new section on emfta. Using the version below, I could not locate the emfta help pages, and searching for emfta yielded zero results. 

  EMFTA 1.0.0.201508132201  edu.cmu.emfta.feature.feature.group SEI/CMU

**Comment by juli1** [comment]
Can you check the help contents (see below) and check you do not have the menu entries?
If this is the case, can you check the installed plugin list and see if you have the edu.cmu.emfta.help installed?

Thanks!

![emftahelp](https://cloud.githubusercontent.com/assets/993972/9286612/f1e000b2-42c4-11e5-827f-9321daaf5b56.png)
![pluginlist](https://cloud.githubusercontent.com/assets/993972/9286613/f1feeb76-42c4-11e5-8f14-d695c6f54841.png)

**Comment by fletchwsf** [comment]
Nothing on the help menu, but the plugs are showing the same files.

![image](https://cloud.githubusercontent.com/assets/7156576/9286675/b00d8022-42c6-11e5-8f4d-bf82b89d8d55.png)

![image](https://cloud.githubusercontent.com/assets/7156576/9286680/c3d9237c-42c6-11e5-8ff6-67b5e19244b3.png)

**Comment by juli1** [comment]
ok, I pushed a new release. Can you give a try? Also, I just added a wizard for EMFTA to create EMFTA models into existing eclipse project. You can have more info here https://github.com/juli1/emfta and in the doc (when it will work).

Thanks for testing!

**Comment by fletchwsf** [comment]
Install the update that you just pushed...no change in the results and
emfta help is still missing.

**Comment by juli1** [comment]
Can you tell me what version of Eclipse or OSATE are you using?

**Comment by fletchwsf** [comment]
Almost.  I just put the computer away for the night.  The Eclipse major
version is Luna, and Osate is one of the last stable releases, 2.1.0 or
2.1.1.  It should be 2.1.1 if Osate will update automatically for 2.1.1
release. ( Juliean's first lesson, "Bill have you updated your installation
lately?").

**Comment by juli1** [comment]
It should be fixed with the last update (related to the update site). Let me know if you see the help.

**Comment by juli1** [comment]
Fixed in the current sources for Mars

**Comment by fletchwsf** [comment]
Help has been found. The Eclipse Mars version of emfta help is working now. Build reference is:
 EMFTA  1.0.0.201508201543  edu.cmu.emfta.feature.feature.group SEI/CMU
